j

diff --git a/gps-t3/Jenkinsfile b/gps-t3/Jenkinsfile
--- a/gps-t3/Jenkinsfile
+++ b/gps-t3/Jenkinsfile
@@ -1,52 +1,29 @@
 pipeline {
-     agent any
-
-      options {
-           buildDiscarder(logRotator(numToKeepStr: '10'))
-      }
-
-      parameters {
-           booleanParam name: 'RUN_TESTS', defaultValue: true, description: 'Run Tests?'
-           booleanParam name: 'RUN_ANALYSIS', defaultValue: true, description: 'Run Static Code Analysis?'
-           booleanParam name: 'DEPLOY', defaultValue: true, description: 'Deploy Artifacts?'
-      }
-
-      stages {
-           stage('Build') {
-                steps {
-                     cmake arguments: '-DCMAKE_TOOLCHAIN_FILE=~/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake', installation: 'InSearchPath'
-cmakeBuild buildType: 'Release', cleanBuild: true, installation: 'InSearchPath', steps: [[withCmake: true]]
-                }
-           }
-
-           stage('Test') {
-                when {
-                     environment name: 'RUN_TESTS', value: 'true'
-                }
-                steps {
-                     ctest 'InSearchPath'
-                }
-
-           }
-
-           stage('Analyse') {
-                when {
-                     environment name: 'RUN_ANALYSIS', value: 'true'
-                }
-                steps {
-                     sh label: '', returnStatus: true, script: 'cppcheck . –xml –language=c++ –suppressions-list=suppressions.txt 2> cppcheck-result.xml'
-                     publishCppcheck allowNoReport: true, ignoreBlankFiles: true, pattern: '**/cppcheck-result.xml'
-                }
-           }
-
-           stage('Deploy') {
-                when {
-                     environment name: 'DEPLOY', value: 'true'
-                }
-                steps {
-                     sh label: '', returnStatus: true, script: '''cp jenkinsexample ~
-                     cp test/testPro ~'''
-                }
-           }
-     }
+    agent any
+    stages {
+        stage('Test') {
+            steps {
+                sh 'echo "Fail!"; exit 1'
+            }
+        }
+    }
+    post {
+        always {
+            echo 'This will always run'
+        }
+        success {
+            echo 'This will run only if successful'
+        }
+        failure {
+            echo 'This will run only if failed'
+        }
+        unstable {
+            echo 'This will run only if the run was marked as unstable'
+        }
+        changed {
+            echo 'This will run only if the state of the Pipeline has changed'
+            echo 'For example, if the Pipeline was previously failing but is now 
+successful'
+        }
+    }
 }
